{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: public
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: enki
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.env "production"}}
  - host: nplan.entur.org
  {{ else }}
  - host: nplan.{{ .Release.Namespace }}.entur.org
  {{- end}}
    http:
      paths:
        - backend:
            serviceName: {{ template "app.name" . }}
            servicePort: {{ .Values.service.http.externalPort }}
{{- end }}
