env: dev

configMap:
  logForwardPaths: "true"
  organisationsApiUrl: https://api.dev.entur.io/timetable-admin/v1/flexible-lines
  publicUrl: /
  uttuApiUrl: https://api.dev.entur.io/timetable-admin/v1/flexible-lines
  auth0Domain: ror-entur-dev.eu.auth0.com
  auth0Client: YBG7NvM9lT3pLmcVKeRZCrPFtU7bll4g
  auth0Audience: https://ror.api.dev.entur.io
  auth0ClaimsNamespace: https://ror.entur.io/role_assignments
  enableLegacyOrganisationsFilter: true
