env: production

replicas: 2

configMap:
  authServerUrl: https://auth.entur.org/auth
  authClientId: enki
  logForwardPaths: "true"
  organisationsApiUrl: https://api.entur.io/organisations/v1/register
  publicUrl: /
  uttuApiUrl: https://api.entur.io/timetable-admin/v1/flexible-lines
  auth0Domain: auth2.entur.org
  auth0Client: VXdzUbFV8ws953UWLrizuaQY9C991w0i
  auth0Audience: https://ror.api.entur.io
  auth0ClaimsNamespace: https://ror.entur.io/role_assignments
  stopPlacesApiUrl: https://api.entur.io/stop-places/v1/graphql
  stopPlacesReadApiUrl: https://api.entur.io/stop-places/v1/read

ingress:
    enabled: true
    productionIp: 104.199.93.228
