env: staging

replicas: 0

configMap:
  authServerUrl: https://kc-stage.devstage.entur.io/auth
  logForwardPaths: "true"
  organisationsApiUrl: https://api.staging.entur.io/organisations/v1/register
  publicUrl: /
  uttuApiUrl: https://api.staging.entur.io/timetable-admin/v1/flexible-lines

ingress:
  enabled: false
